stages:
  - build


# --- Build ---

android build sdk:
  image: alvrme/alpine-android:android-34-jdk17
  stage: build
  artifacts:
    expire_in: 8 hours
    paths:
      - java/app/build/outputs/apk/release
      - kotlin/app/build/outputs/apk/release
  script:
    - pushd java
    - echo "verifaiLicense=\"dummy\"" > secret.properties
    - ./gradlew app:build
    - popd
    - pushd kotlin
    - echo "verifaiLicense=\"dummy\"" > secret.properties
    - ./gradlew app:build
